name: python-application-pr

env:
  AZURE_WEBAPP_NAME: python-postgres-azure
  PYTHON_VERSION: "3.13"

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conventional-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3

  linting-pr:
    runs-on: ubuntu-latest
    needs:
      - conventional-commit-check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: pip install black flake8

      - name: Check Formatting and linting
        run: black ./ --check && flake8

  static-code-analysis-pr:
    runs-on: ubuntu-latest
    needs:
      - linting-pr
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: pip install bandit

      - name: SAST
        run: bandit -r ./rates -c .bandit.yaml

  dependency-vulnerability-analysis-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rates
    needs:
      - linting-pr
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: pip install safety

      - name: Safety Check
        run: safety check --file requirements.txt.lock --full-report

  bdd-test-pr:
    runs-on: ubuntu-latest
    needs:
      - linting-pr
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Run Behave BDD Tests
        run: |
          make start-app-db
          pip install behave requests
          echo "****** Running behave tests ******"
          behave
          make stop-app-db
